version: '3.9'
services:
  aadexpiredappchecker:
    container_name: aadexpiredappchecker
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/app
    